---
title: "Untitled"
author: "eNVy"
date: "3/18/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}


setwd("~/crime/")

library(tidyverse)

df <- read_csv("NYPD_Complaint_Data_Current_YTD (1).csv")
df_des <- read_csv("NYPD_Incident_Level_Data_Column_Descriptions.csv")

df %>% head() %>% names(
  
)

```

```{r}
df2 <- df %>% 
  select(-all_of(c(1, 4, 5, 6, 9, 10, 20, 21)))
```

```{r}
df2 %>% head()
```

```{r}
df2 %>% 
  select(KY_CD, OFNS_DESC) %>% transmute(
    response = as.factor(KY_CD), 
    name = OFNS_DESC
  ) %>% group_by(name) %>% 
  summarise(count = n()) %>% arrange(name) %>% View()
```



```{r}
df2 %>% 
  select(OFNS_DESC) %>% 
  mutate(
    collpsed = OFNS_DESC %>%  fct_collapse(
      ADMINISTRATIVE_CODE = c("ADMINISTRATIVE CODE", "ADMINISTRATIVE CODES"),
      Burglary = c("BURGLAR'S TOOLS", "BURGLARY"), 
      forgery = c("FORGERY", "FRAUDS", "FRAUDULENT ACCOSTING", "THEFT-FRAUD", "OFFENSES INVOLVING FRAUD"),
      grand_larceny = c("GRAND LARCENY", "GRAND LARCENY OF MOTOR VEHICLE"),
      petit_larceny = c("PETIT LARCENY", "PETIT LARCENY OF MOTOR VEHICLE"),
      state_laws = c("OTHER STATE LAWS", "OTHER STATE LAWS (NON PENAL LA", "OTHER STATE LAWS (NON PENAL LAW)", "VEHICLE AND TRAFFIC LAWS", "AGRICULTURE & MRKTS LAW-UNCLASSIFIED", "ALCOHOLIC BEVERAGE CONTROL LAW", "NYS LAWS-UNCLASSIFIED FELONY", "NYS LAWS-UNCLASSIFIED VIOLATION"),
      sex_crimes = c("PROSTITUTION & RELATED OFFENSES", "RAPE", "SEX CRIMES"), 
      kidnapping = c("KIDNAPPING", "KIDNAPPING & RELATED OFFENSES"), 
      ROBBERY = c("ROBBERY", "THEFT OF SERVICES", "OTHER OFFENSES RELATED TO THEF", "POSSESSION OF STOLEN PROPERTY"),
      Offences = c("OFF. AGNST PUB ORD SENSBLTY &", "OFFENSES AGAINST PUBLIC ADMINI", "OFFENSES AGAINST THE PERSON"),
      
    )
  ) %>% select(collpsed) %>% 
  mutate(
    collpsed = collpsed %>% fct_collapse(
      ROBBERY = c("ROBBERY", "Burglary"), 
      Penal_law = c("MISCELLANEOUS PENAL LAW", "state_laws", "INTOXICATED & IMPAIRED DRIVING", "CRIMINAL TRESPASS", "UNAUTHORIZED USE OF A VEHICLE"), 
      DANGEROUS_DRUG_weapons = c("DANGEROUS DRUGS", "DANGEROUS WEAPONS")
    )
  ) %>% 
  group_by(collpsed) %>% 
  summarise(count = n()) %>% filter(count > 800) %>% 
  arrange(desc(count)) %>% View()
```




