---
title: "Initial"
author: "eNVy"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = NA,
                      fig.width = 5, fig.height = 4)
```

```{r libs, message=F, warning=F}
library(tidyverse)
library(magrittr)
library(lubridate)
library(sf)
library(tmap)

df_raw <- read_csv("../Data/crime.csv")
trend_raw <- read_csv("../Data/googletrend.csv")
shp_raw <- sf::st_read("../Data/local-area-boundary.shp")

```

# Initial Peak

```{r}
df_raw %>% sample_n(10)
```

| Col1 | Col2 |
|------|------|
|      |      |
|      |      |

```{r}
# the hell is this?
trend_raw %>% 
  sample_n(10)
```


## NA counts

```{r}
df_raw %>% 
  sample_n(1000) %>% 
  is.na() %>% 
  table()
```
True NA count

| FALSE | TRUE |
|-------|------|
|6202463|165361|


```{r}

df_raw %>% 
  transmute(
    TYPE = as.factor(TYPE)
  )  %>% pull(TYPE) %>% 
  fct_infreq() %>% 
  fct_rev() %>% 
  fct_count() %>% 
  ggplot(aes(x = f, y = n, fill = f)) + 
  geom_col(show.legend = F) +  
  coord_flip()
```

TODO:

-   Class imbalance
-   `library(sf)`, `html widget` to visualize the geological aspect

# Dataset fix

```{r}
df_raw %<>% 
  rename_all(tolower)
```



```{r}
df_raw %>% 
  mutate(
    type = as.factor(type) %>% fct_infreq()
  ) %>% 
  filter(type != "Theft from Vehicle" & type != "Homicide") -> new

new$type %>% fct_drop() %>% 
  fct_count()
```

```{r}
levels(new$type)[c(6,8)] = "theft of something"
levels(new$type)[c(8,9)] = "vehicle collision"

```

# shape file

```{r}
shp_raw %>% head()
```

```{r}
tmap_mode("view")

tm_shape(shp_raw) + 
  tm_borders() 
# add geometry to df_raw 
# so that we can do a geom_sf() + on top of geom_point()
# 
```


```{r, fig.width= 7, fig.height=8}
new %>% sample_n(100000) %>% 
  filter(latitude > 49.1549 & longitude < -123 & latitude < 49.4) %>% 
  ggplot(aes(x = longitude, y = latitude)) + 
  geom_point(aes(col = type), show.legend = F)
```

